### ISSUE TITLE
Error renaming folder

### ISSUE THREAD

**Issue by duarteframos** [pmarinov/rrss#9]
I get this while trying to rename a folder

Unfortunatelly the program "rrss" crashed
Please consider making a bug report together with this information.
ASSERT: missing field "hideAreaFeedErrors"; in p_hideUnhideSections

source file: app.html:0:0
stack: 
`ReferenceError: i is not defined
    at assert (rrss/utils.js:299:7)
    at Object.hasFields (rrss/utils.js:323:7)
    at FeedsDir.p_hideUnhideSections (rrss/feeds_dir.js:572:12)
    at HTMLButtonElement. (rrss/feeds_dir.js:243:14)
    at HTMLButtonElement.dispatch (lib/jquery-2.0.2.js:4692:9)
    at HTMLButtonElement.elemData.handle (lib/jquery-2.0.2.js:4376:28)`

**Comment by pmarinov** [comment]
Thank you for reporting this problem and submitting the crash-stack information.

I see that the "Cancel" button has a bug in the implementation. It will be fixed in the next release.

**Comment by duarteframos** [comment]
Most welcome

**Comment by pmarinov** [comment]
Fixed in version 0.8.0

**Comment by duarteframos** [comment]
Thanks for the fix :)
